
[Host Firewall Status Change History]
action.email.useNSSubject = 1
action.webhook.enable_allowlist = 0
alert.track = 0
dispatch.earliest_time = -7d@h
dispatch.latest_time = now
display.general.type = statistics
display.page.search.mode = verbose
display.page.search.tab = statistics
display.visualizations.show = 0
request.ui_dispatch_app = windows_pfirewall_app
request.ui_dispatch_view = search
search = index IN `windows_firewall_index` source="*WinEventLog:Microsoft-Windows-Windows Firewall With Advanced Security/Firewall" EventID IN (2082,2083,2003) status != "N/A"\
| table _time SystemTime Computer status

[Host Firewall All Changes History]
search = index IN `windows_firewall_index` source="*WinEventLog:Microsoft-Windows-Windows Firewall With Advanced Security/Firewall" NOT EventID="2010"\
| eval Action = if(isnull(Action), "N/A", Action) \
| lookup windows_firewall_event_id EventID \
| eval Description = case((EventID="2082" OR EventID="2003") AND SettingType="1", "Enable Windows Defender Firewall" + ": " + SettingValueString, true(), Description)\
| table _time Computer EventID Description\
    ModifyingApplication ModifyingUser RuleName action status ApplicationPath Direction Protocol LocalAddresses LocalPorts RemoteAddresses RemotePorts OldProfile NewProfile \
| sort - _time

[Windows Host Firewall traffic History]
action.email.useNSSubject = 1
action.webhook.enable_allowlist = 0
alert.track = 0
dispatch.earliest_time = -7d@h
dispatch.latest_time = now
display.general.type = statistics
display.page.search.mode = fast
display.page.search.tab = statistics
display.visualizations.show = 0
request.ui_dispatch_app = windows_pfirewall_app
request.ui_dispatch_view = search
search = index IN `windows_firewall_index` sourcetype="windows:pfirewall" `ip_whitelist` | iplocation src_ip prefix=src_ | iplocation dest_ip prefix=dest_ | eval src_Country = case(isnull(src_Country), "N/A", true(), src_Country) | eval dest_Country = case(isnull(dest_Country),  "N/A", true(), dest_Country) | search host IN (*) dest_port IN (*) (src_ip IN (*) OR dest_ip IN (*)) | stats count by host src_ip src_Country dest_ip dest_Country dest_port action
