#
# Splunk app configuration file
#

[install]
is_configured = 0

[package]
id = windows_firewall_app
check_for_updates = true

[ui]
is_visible = 1
show_in_nav = true
label = Microsoft Windows Firewall Observability
setup_view = setup_page_dashboard

[launcher]
author = Amara TRAORE
description = This App was designed to collect, parse, format and visualize data from your windows host (Workstation or server) firewall Traffic and configuration changes activities. This App contain configurations for data inputs, field extractions, and others knowledge objects cim compliant that enhance detections and investigations capabilities within Splunk.
version = 2.0.0

[id]
version = 2.0.0
name = windows_firewall_app

