[monitor://C:\Windows\System32\LogFiles\Firewall\pfirewall.log]
disabled = 0
index = default
sourcetype = windows:pfirewall

[WinEventLog://Microsoft-Windows-Windows Firewall With Advanced Security/Firewall]
disabled = 0
renderXml = 1
index = default
