
[eventtype=traffic]
communicate = enabled
network = enabled

[eventtype=windows_firewall]
change = enabled

[eventtype=firewall_setting]
change = enabled
endpoint = enabled

[eventtype=firewall_rule_change]
change = enabled
endpoint = enabled

[eventtype=firewall_service_status]
audit = enabled