#
# TA-wallix-bastion - tags.conf
# CIM data model tags, attached through eventtypes.
#

[eventtype=wallix_bastion_authentication]
authentication = enabled

[eventtype=wallix_bastion_authentication_privileged]
authentication = enabled
privileged = enabled

[eventtype=wallix_bastion_session_authentication]
authentication = enabled
privileged = enabled

[eventtype=wallix_bastion_authentication_default]
authentication = enabled
default = enabled

[eventtype=wallix_bastion_change]
change = enabled

[eventtype=wallix_bastion_account_management]
change = enabled
account = enabled

[eventtype=wallix_bastion_authorization_change]
change = enabled

[eventtype=wallix_bastion_vault_activity]
change = enabled
account = enabled

[eventtype=wallix_bastion_backup]
change = enabled

[eventtype=wallix_bastion_network_traffic]
network = enabled
communicate = enabled

[eventtype=wallix_bastion_session_traffic]
network = enabled
communicate = enabled
session = enabled
start = enabled

[eventtype=wallix_bastion_session_end]
network = enabled
session = enabled
end = enabled

[eventtype=wallix_bastion_process_activity]
process = enabled
report = enabled
endpoint = enabled
