#
# Microsoft Windows Firewall Observability
#

[install]
is_configured = 0
state = enabled
build = 310

[package]
id = windows_firewall_app
check_for_updates = true

[ui]
is_visible = 1
show_in_nav = true
label = Microsoft Windows Firewall Observability
setup_view = setup_page_dashboard

[launcher]
author = Amara TRAORE
description = Collect, parse, normalise and visualise Windows Defender Firewall traffic, process attribution and configuration posture. CIM compliant knowledge objects, an accelerable data model, eight Dashboard Studio views and twenty-four ready-to-use detections and reports.
version = 3.1.0

[id]
name = windows_firewall_app
version = 3.1.0

[triggers]
reload.macros = simple
reload.savedsearches = simple
reload.eventtypes = simple
reload.tags = simple
reload.transforms = simple
reload.props = simple
