##############################################################################
# Microsoft Windows Firewall Observability - tags.conf
##############################################################################

# CIM: Network Traffic
[eventtype=windows_firewall_traffic]
network = enabled
communicate = enabled

# CIM: Change
[eventtype=windows_firewall_change]
change = enabled
endpoint = enabled

[eventtype=windows_firewall_setting_change]
change = enabled
endpoint = enabled
configuration = enabled

[eventtype=windows_firewall_rule_change]
change = enabled
endpoint = enabled
policy = enabled

[eventtype=windows_firewall_service_status]
change = enabled
endpoint = enabled
audit = enabled

# CIM: Network Traffic - Windows Filtering Platform
[eventtype=windows_firewall_wfp_connection]
network = enabled
communicate = enabled

[eventtype=windows_firewall_wfp_listen]
network = enabled
endpoint = enabled

# CIM: inventory of the firewall posture
[eventtype=windows_firewall_posture_profile]
network = enabled
endpoint = enabled

[eventtype=windows_firewall_posture_rule]
policy = enabled
endpoint = enabled
