
[traffic]
search = (index=* source="C:\\Windows\\System32\\LogFiles\\Firewall\\pfirewall.log" NOT info="-")
color = none

[windows_firewall]
search = (index=* source="*WinEventLog:Microsoft-Windows-Windows Firewall With Advanced Security/Firewall")

[firewall_setting]
search = (index=* source="*WinEventLog:Microsoft-Windows-Windows Firewall With Advanced Security/Firewall") EventID IN ("2082","2003")

[firewall_rule_change]
search = (index=* source="*WinEventLog:Microsoft-Windows-Windows Firewall With Advanced Security/Firewall") EventID IN ("2052","2097","2099","2006","2004","2005")

[firewall_service_status]
search = (index=* source="*WinEventLog:Microsoft-Windows-Windows Firewall With Advanced Security/Firewall") SettingType=1